import { WikiArticle } from './types';

export const CHICKEN_WIKI: WikiArticle[] = [
  {
    id: '1',
    title: 'Egg Harvesting Basics',
    category: 'Harvesting',
    content: 'Collect eggs at least once a day, preferably in the morning. Check nesting boxes frequently to prevent breakage and egg-eating habits.'
  },
  {
    id: '2',
    title: 'Chick Hatching Guide',
    category: 'Hatching',
    content: 'Incubation takes 21 days. Maintain a steady temperature of 99.5°F (37.5°C) and humidity around 50-55% for the first 18 days.'
  },
  {
    id: '3',
    title: 'Raising Healthy Pullets',
    category: 'Raising',
    content: 'Pullets need high-protein starter feed for the first 8 weeks. Ensure they have a warm, draft-free brooder with plenty of fresh water.'
  },
  {
    id: '4',
    title: 'General Hen Wellbeing',
    category: 'Wellbeing',
    content: 'A happy hen needs space to dust bathe, fresh greens, and a secure coop to protect from predators. Regularly check for mites and lice.'
  }
];

export const CHICKEN_FACTS = [
  "Chickens can recognize over 100 different faces of their own species.",
  "A mother hen talks to her chicks before they've even hatched.",
  "Chickens have full-color vision, just like humans.",
  "The record for the most eggs laid by a chicken in one day is 7.",
  "Chickens are the closest living relative to the Tyrannosaurus Rex.",
  "A chicken's heart beats 220 to 360 times per minute.",
  "Chickens have more than 30 different types of vocalizations.",
  "The fear of chickens is called Alektorophobia.",
  "Chickens can see ultraviolet light.",
  "A chicken can live for several minutes without its head.",
  "The world record for the most yolks in a single chicken egg is 9.",
  "Chickens are omnivores and will eat lizards, mice, and even other chickens if food is scarce.",
  "A hen can lay around 300 eggs per year.",
  "Chickens have three eyelids for each eye.",
  "The oldest chicken on record lived to be 16 years old.",
  "Chickens can experience REM sleep, meaning they dream just like us.",
  "A chicken's beak is very sensitive to touch.",
  "Chickens use their combs to regulate their body temperature.",
  "The color of a chicken's earlobe can often tell you what color egg it will lay.",
  "Chickens can swim, but they don't have webbed feet so they aren't very good at it.",
  "Why did the chicken cross the road? To prove to the possum it could be done!",
  "What do you call a bird that's afraid of heights? A chicken!",
  "How do chickens get strong? Egg-ercise!",
  "What do you call a chicken that's good at math? A mathe-ma-chicken!",
  "Why did the chicken go to the seance? To get to the other side!",
  "What do you call a group of chickens clucking in unison? A hen-semble!",
  "Why don't chickens like people? Because they're always egg-ing them on!",
  "What do you call a chicken with a piece of lettuce in its eye? The tip of the iceberg!",
  "Why did the chicken cross the playground? To get to the other slide!",
  "What do you call a chicken that's a great dancer? A poultry-in-motion!",
  "Chickens can run up to 9 miles per hour.",
  "A hen will turn her egg about 50 times a day to keep the yolk from sticking to the shell.",
  "Chickens have a 'pecking order' that determines social hierarchy.",
  "The first chicken ever to be domesticated was in Southeast Asia around 7,000 years ago.",
  "Chickens can sense the Earth's magnetic field to help them navigate.",
  "A chicken's brain is about the size of a walnut.",
  "Chickens can remember and distinguish between different people.",
  "The most popular breed of chicken in the world is the Rhode Island Red.",
  "Chickens can be trained to perform simple tasks and tricks.",
  "A chicken's feathers are waterproof to help keep them dry in the rain.",
  "Chickens have a very keen sense of hearing.",
  "The world's largest chicken egg weighed over 1 pound.",
  "Chickens can live in a wide variety of climates, from very cold to very hot.",
  "A chicken's diet can affect the color of its egg yolk.",
  "Chickens are very social animals and enjoy the company of other chickens.",
  "The sound a chicken makes is called a 'cluck'.",
  "Chickens can be very protective of their young.",
  "A chicken's life span is typically 5 to 10 years.",
  "Chickens are a very important source of food for humans all over the world.",
  "The chicken is the most common bird in the world.",
  "Chickens have a very complex social structure.",
  "A chicken's eyes are on the sides of its head, giving it a wide field of vision.",
  "Chickens can see better in the dark than humans can.",
  "The word 'chicken' comes from the Old English word 'cicen'.",
  "Chickens have been featured in many myths and legends throughout history.",
  "A chicken's comb is a sign of its health and vitality.",
  "Chickens can be very curious and enjoy exploring their environment.",
  "The chicken is a very resilient animal and can recover from many illnesses.",
  "Chickens are a very important part of many ecosystems.",
  "A chicken's presence can help to reduce the number of pests in a garden.",
  "Chickens can be very affectionate and enjoy being petted.",
  "The chicken is a very intelligent animal and can learn many things.",
  "Chickens have a very strong sense of community.",
  "A chicken's cluck can convey many different meanings.",
  "Chickens are a very versatile animal and can be used for many different purposes.",
  "The chicken is a very hardy animal and can withstand many challenges.",
  "Chickens can be very entertaining to watch.",
  "A chicken's feathers can be used for many different things, such as pillows and clothing.",
  "Chickens are a very important part of many cultures around the world.",
  "The chicken is a very fascinating animal and there is still much to learn about it.",
  "What do you call a chicken that's a detective? Sherlock Hens!",
  "Why did the chicken join a band? Because it had the drumsticks!",
  "What do you call a chicken that's a ghost? A poultry-geist!",
  "How does a chicken mail a letter? In a hen-velope!",
  "Why did the chicken cross the road twice? Because it was a double-crosser!",
  "What do you call a chicken that's a comedian? A funny-bone!",
  "Why did the chicken go to the library? To look for some 'egg-citing' books!",
  "What do you call a chicken that's a doctor? A 'quack'!",
  "Why did the chicken cross the road? To get to the other 'egg-it'!",
  "What do you call a chicken that's a superhero? Super-Hen!",
  "Why did the chicken go to the gym? To work on its 'peck-toral' muscles!",
  "What do you call a chicken that's a musician? A 'cluck-star'!",
  "Why did the chicken cross the road? To show the world it wasn't 'chicken'!",
  "What do you call a chicken that's a chef? A 'fry-er'!",
  "Why did the chicken go to the beach? To get some 'sun-ny' side up!",
  "What do you call a chicken that's a pilot? A 'fly-er'!",
  "Why did the chicken cross the road? To get to the 'cluck-in' donuts!",
  "What do you call a chicken that's a scientist? An 'egg-sperimenter'!",
  "Why did the chicken go to the party? To have an 'egg-cellent' time!",
  "What do you call a chicken that's a teacher? An 'egg-ucator'!",
  "Why did the chicken cross the road? To get to the 'hen-house'!",
  "What do you call a chicken that's a lawyer? A 'beak-er'!",
  "Why did the chicken go to the movies? To see the latest 'cluck-buster'!",
  "What do you call a chicken that's a writer? A 'pen-hen'!",
  "Why did the chicken cross the road? To get to the 'egg-stravaganza'!",
  "What do you call a chicken that's a gardener? A 'cluck-ivator'!",
  "Why did the chicken go to the spa? To get a 'feather' treatment!",
  "What do you call a chicken that's a photographer? A 'snap-hen'!",
  "Why did the chicken cross the road? To get to the 'egg-it' ramp!",
  "What do you call a chicken that's a fashionista? A 'cluck-ture' model!"
];

export const DEFAULT_LOCATIONS = [
  { id: 'loc-1', name: 'Cluckingham Palace', type: 'Garden' },
  { id: 'loc-2', name: 'The Yolk Yard', type: 'Allotment' }
];
